---
- hosts: all
  
  tasks:
  - name: ensure directory exists
    file:
      path: /tmp/test_dir34
      state: directory
  - name: ensure file exists
    command: touch test_file67
    args:
      chdir: /tmp/test_dir 
    
...
