---
- hosts: localhost
  tasks:
    - name: Set a fact
      set_fact:
        our_fact: Hello Ansible
        ansible_distribution: "{{Rakuten Intern |upper}}"

    - name: Show our fact
      debug:
        msg: "{{our_fact}}"
    - name: Show ansible_distribution
      debug:
        msg: "{{ansible_distribution}}"
...
